# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='Tag',
        ),
    ]
